vim.cmd([[inoremap " ""<left>]])
vim.cmd([[inoremap ' ''<left>]])
vim.cmd([[inoremap ' ''<left>]])
vim.cmd([[inoremap ' ''<left>]])
vim.cmd([[inoremap ' ''<left>]])
vim.cmd([[inoremap [ []<left>]])
vim.cmd([[inoremap { {}<left>]])
vim.cmd([[inoremap ( ()<left>]])
vim.cmd([[nnoremap <C-s> :w<CR>]])
vim.cmd([[nnoremap <C-q> :q<CR>]])
vim.cmd([[nnoremap <C-x> :x<CR>]])
vim.cmd([[nnoremap e w]])
vim.cmd([[nnoremap x d]])
vim.cmd([[nnoremap g gg]])
vim.cmd([[noremap <C-R> :call Runner()<CR>]])
vim.cmd([[nnoremap <silent><C-T> :FloatermNew<CR>]])
vim.cmd([[nnoremap <silent><C-N> :NvimTreeToggle<CR>]])
